---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qor.fullname" . }}
data:
  {{- with .Values.env }}
  {{- range . }}
  {{ .name }}: "{{ .value }}"
  {{- end }}
  {{- end }}

---

apiVersion: v1
data:
  application.example.yml: |
    github:
      clientid: "your github client id"
      clientsecret: "your github client secret"
    google:
      clientid: "your google client id"
      clientsecret: "your google client secret"
    facebook:
      clientid: "your facebook client id"
      clientsecret: "your facebook client secret"
    twitter:
      clientid: "your twitter client id"
      clientsecret: "your twitter client secret"

    cron:
      expireaftersales: "* */2 * * * *"
      freezeauditedaftersales: "* */2 * * * *"
      unfreezeaftersales: "* */2 * * * *"
      updatebalances: "* */2 * * * *"
      autoexportmobilephones: "0 0 1 * * *"
      autoexportorderdetails: "0 0 1 * * *"
      autoexportorderfollowups: "0 0 1 * * *"
      autoexportorderfees: "0 */1 * * * *"
      autoupdateorderitems: "0 */5 * * * *"
      autodeliverorders: "0 0 1 * *"

      autoinquire: "*/30 * * * * *"
      autoschedule: "0 */5 * * * *"
      autoprocess: "0 */2 * * * *"
      autofinish: "0 */2 * * * *"
      autoaudit: "0 */1 * * * *"
      autowithdraw: "0 */5 * * * *"
      autoaward: "0 */6 * * * *"
      autofine: "0 */7 * * * *"
      autogenerateaftersales: "0 */30 * * * *"
kind: ConfigMap
metadata:
  name: application.yaml

---
apiVersion: v1
data:
  smtp.yml: |
    smtp:
      host: smtp.gmail.com
      port: 587
      user: qor@getqor.com
      password: xxxxxx
      site: http://demo.getqor.com

kind: ConfigMap
metadata:
  name: smtp.yaml
