apiVersion: v1
kind: Service
metadata:
  name: {{ include "qor.fullname" . }}
  labels:
    {{- include "qor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7000
      protocol: TCP
      name: http
  selector:
    {{- include "qor.selectorLabels" . | nindent 4 }}
